OpenCollective post
boa-dev/boa-dev.github.io pull request #22
Opened 2022-02-26 20:33 UTC by Razican

This adds the post for the OpenCollective organisation. Still in draft.

2022-02-26 20:47 UTC, jedel1043 requested changes

2022-02-26 20:47 UTC, jedel1043 commented on _posts/2022-03-01-boa-open-collective.md
> +financially. From now on, anyone can contribute with either a recurring donationk, or a one-time contribution in our
```suggestion
financially. From now on, anyone can contribute with either a recurring donation, or a one-time contribution in our
```

2022-02-26 20:47 UTC, jedel1043 commented on _posts/2022-03-01-boa-open-collective.md
> +want to spend more of our free time in boa, and receiving a financial compensation for it is definitely makin the team
```suggestion
want to spend more of our free time in boa, and receiving a financial compensation for it is definitely making the team
```

2022-02-26 20:47 UTC, jedel1043 commented on _posts/2022-03-01-boa-open-collective.md
> +engine, but they have a high variability (up to 10%). This means that we can definitely see changes if they are big, but it's
```suggestion
actions for benchmarking, which is useful to get some general ideas on how some changes affect the performance of the
engine. However, they have a high variability (up to 10%), meaning that we can definitely see changes if they are big, but it's
```

2022-02-26 21:16 UTC, RageKnify approved these changes
I like jedel's suggestions, don't have anything else to add.

2022-02-26 21:16 UTC, RageKnify commented on _posts/2022-03-01-boa-open-collective.md
> +In the past months, due to the big and steady progress on Boa, we have received multiple requests to contribute with Boa
```suggestion
In the past months, due to the big and steady progress on Boa, we have received multiple requests to contribute to Boa
```

2022-03-01 12:01 UTC, HalidOdat approved these changes
This looks perfect to me! :)

2022-03-01 16:09 UTC, jedel1043 approved these changes

2022-03-01 20:35 UTC, Razican commented
Merged with #20.

2022-03-01 20:35 UTC, closed without merging